#!/bin/bash

get_package_dependencies_changes () {
  local CURRENT_BRANCH
  CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

  git diff HEAD~1..HEAD~0 -- "origin/$CURRENT_BRANCH" package.json | grep \
    -e '+\s*\"shinkansen-rails\":\s\".*"' \
    -e '+\s*\"shinkansen-signals\":\s\".*"' \
    -e '+\s*\"shinkansen-transmission\":\s\".*"'
}

has_package_dependencies_changes () {
  [ ! -z "$(get_package_dependencies_changes)" ]
}

if has_package_dependencies_changes;
then
  git clone https://github.com/modernpoacher/hooks.git .husky/hooks
  npx cross-env DEBUG=@modernpoacher/hooks* node .husky/hooks/post-commit.mjs
  rm -rf .husky/hooks
fi
