#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

get_package_version_changes () {
  git diff HEAD~1..HEAD~0 -- origin/main package.json | grep -e '+\s*\"version\":\s\".*"'
}

has_package_version_changes () {
  [ ! -z "$(get_package_version_changes)" ]
}

get_package_dependencies_changes () {
  git diff HEAD~1..HEAD~0 -- origin/main package.json | grep \
    -e '+\s*\"shinkansen-rails\":\s\".*"' \
    -e '+\s*\"shinkansen-signals\":\s\".*"' \
    -e '+\s*\"shinkansen-transmission\":\s\".*"'
}

has_package_dependencies_changes () {
  [ ! -z "$(get_package_dependencies_changes)" ]
}

if ! has_package_version_changes;
then
  if has_package_dependencies_changes;
  then
    npx cross-env DEBUG=@modernpoacher/hooks* node .husky/post-commit.mjs
  fi
fi
